export const SET_FORM_STATE = 'SET_FORM_STATE'
export const SET_EDIT_ITEM = 'SET_EDIT_ITEM'
export const SET_REGION = 'SET_REGION'
export const CREATE_REGION = 'CREATE_REGION'
export const UPDATE_REGION = 'UPDATE_REGION'
export const DELETE_REGION = 'DELETE_REGION'
export const ADD_REGION = 'ADD_REGION'
export const SET_CLUSTER = 'SET_CLUSTER'

export const types = {
  admin: {
    ADMIN_CREATE_REGION: 'ADMIN_CREATE_REGION',
    ADMIN_UPDATE_REGION: 'ADMIN_UPDATE_REGION',
    ADMIN_DELETE_REGION: 'ADMIN_DELETE_REGION',
    ADMIN_ADD_REGION: 'ADMIN_ADD_REGION',
    ADMIN_REMOVE_REGION: 'ADMIN_ADD_REGION',
    ADMIN_SET_REGION: 'ADMIN_SET_REGION'
  },
  partner: {
  }
}
