export const SET_FORM_STATE = 'SET_FORM_STATE'
export const SET_EDIT_ITEM = 'SET_EDIT_ITEM'
export const SET_CLUSTER = 'SET_CLUSTER'

export const types = {
  admin: {
    ADMIN_REGION_CREATE: 'ADMIN_REGION_CREATE',
    ADMIN_REGION_UPDATE: 'ADMIN_REGION_UPDATE',
    ADMIN_REGION_DELETE: 'ADMIN_REGION_DELETE',
    ADMIN_REGION_SET: 'ADMIN_REGION_SET',
    ADMIN_REGION_SET_ITEM: 'ADMIN_REGION_SET_ITEM',
    ADMIN_REGION_ADD: 'ADMIN_REGION_ADD',
    ADMIN_REGION_REMOVE: 'ADMIN_REGION_REMOVE'
  },
  partner: {
  }
}
